config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :organizations
  resources :applications do
    collection do
      patch 'bulk_action'
    end
  end
  resources :applications
  root 'pages#home'
  get "/", to: "pages#home"
  # Add basic UI for viewing applications
  devise_for :users
  resources :faculties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
# frozen_string_literal: true

class Application < ApplicationRecord
  include AASM
  include ActiveModel::Validations

  has_many :experiences, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_many :schedule_items, dependent: :destroy
  has_many :user_applications, dependent: :destroy
  has_many :users, through: :user_applications, inverse_of: :application
  has_many_attached :files
  belongs_to :organization
  accepts_nested_attributes_for :experiences
  accepts_nested_attributes_for :roles
  accepts_nested_attributes_for :schedule_items
  accepts_nested_attributes_for :users
  validates :name, presence: true
  validates :coordinator, presence: true
  validates :amount_applied_for, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :amount_other_sources, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :amount_overall, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates_with TotalSumValidator
  validates :date, presence: true
  validates_date :date, on_or_before: lambda { Time.zone.today }
  aasm do
    state :pending, initial: true
    state :accepted, :rejected

    event :accept do
      transitions from: %i[pending rejected accepted], to: :accepted
    end

    event :reject do
      transitions from: %i[pending rejected accepted], to: :rejected
    end

    # event :pending do
    #   transitions from: %i[pending accepted rejected], to: :pending
    # end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/applications_controller.rb
# frozen_string_literal: true

class ApplicationsController < ApplicationController
  include Pundit
  rescue_from Pundit::NotAuthorizedError do |_exception|
    flash[:alert] = t("pundit.errors.user_not_authorized")
    redirect_to request.referer || root_path
  end
  before_action :authenticate_user!
  before_action :set_application, only: %i[show update]
  after_action :verify_policy_scoped
  after_action :verify_authorized, only: :update

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  wrap_parameters include: %i[selections decision organization_id], format: %i[json xml url_encoded_form multipart_form]

  def index
    @applications = policy_scope(Application)
    @applications = @applications.order(:updated_at)
  end

  def new
    @organization = policy_scope(Organization)
    @users = User.all
    @application = Application.new
    @application.amount_applied_for = 0
    @application.amount_other_sources = 0
    @application.amount_overall = 0
    3.times { @application.experiences.build }
    3.times { @application.schedule_items.build }
    3.times { @application.roles.build }
  end

  def create
    @organization = policy_scope(Organization).find(application_params[:organization_id])
    @application = @organization.applications.new(application_params)
    if @application.save
      flash[:notice] = t('.created_successfully')
      redirect_to @application
    else
      flash[:alert] = t('.not_created')
      render 'new'
    end
  end

  def edit
    @organization = policy_scope(Organization)
    @users = User.all
    @application = policy_scope(Application).find(params[:id])
  end

  def show
    @application = policy_scope(Application).find(params[:id])
  end

  # TODO: restrictions for fsm state transitions in form of
  # user errors i.e. "Application already accepted" or "Can't accept rejected"
  def update
    @application = policy_scope(Application).find(params[:id])

    @application.schedule_items.clear
    @application.experiences.clear
    @application.roles.clear

    policy_scope(Application).update(@application.id, application_params)
    authorize @application
    if params[:application][:decision] == 'update'
      if @application.save
        flash[:notice] = t('.successfully_updated')
      else
        flash[:alert] = t('.not_created')
      end
    elsif params[:decision] == 'accept'
      @application.accept!
      flash[:notice] = t('.accepted')
    elsif params[:decision] == 'reject'
      @application.reject!
      flash[:notice] = t('.rejected')
    else
      flash[:alert] = t('.cant_change_state')
    end
    redirect_to applications_path
  end

  def bulk_action
    # You can access bulk_action_params[:application_ids] here
    # You also need to add this action to config/routes.rb
    @application = policy_scope(Application).find(params[:selections].split(','))
    @application.each do |app|
      authorize app
      if params[:decision] == 'accept'
        app.accept!
        flash[:notice] = t('.accepted')
      elsif params[:decision] == 'reject'
        app.reject!
        flash[:notice] = t('.rejected')
      else
        flash[:alert] = t('.cant_change_state')
      end
    end
    redirect_to applications_path
  end

  private

  def set_application
    @application = Application.find(params[:id])
  end

  def bulk_action_params
    params.require(:application).permit(application_ids: [])
  end

  def application_params
    params.require(:application).permit(
      :name,
      :coordinator,
      :user_id,
      :amount_applied_for,
      :amount_other_sources,
      :amount_overall,
      :organization_id,
      :description,
      :location,
      :date,
      :required_resources,
      :past_schedule,
      :collaborations,
      :target_group,
      :sponsor_enlistment,
      :promotion_plans,
      :current_state,
      :project_subject,
      :collaboration,
      experiences_attributes: %i[project_name role budget project_date member_name],
      schedule_items_attributes: %i[todo start start_date due_date],
      roles_attributes: %i[member_role first_name last_name],
      files: []
    )
  end

  def user_not_authorized
    flash[:alert] = t('.user_not_authorized')
    redirect_to @application
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-warning"
    end
  end
end

app/helpers/applications_helper.rb
# frozen_string_literal: true

module ApplicationsHelper
end

app/views/applications/_experiences_fields.html.haml
// TODO can this div be a row? layout dillemas
= content_tag :div, class: "nested-fields", data: { new_record: f.object.new_record? } do
  .container.experiences_row.w-100.my-4.p-3.border.border-secondary
    .row
      .col-md-4
        = f.input :project_name, label: t(".project_name")
      .col-md-4
        = f.input :role, label: t(".role")
      .col-md-4
        = f.input :budget, input_html: { min: '0',
        required: true,  oninput: "this.value = Math.abs(this.value)",
        placeholder: 0},
        label: t(".budget")
    .row
      .col-md-6
        = f.input :project_date, label: t(".project_date")
      .col-md-6
        = f.input :member_name, label: t(".member_name")
    %small= link_to t('.remove_experience_item'), "#", class: "btn btn-primary", data: { action: "click->nested-form#remove_association" }
    = f.hidden_field :_destroy

app/views/applications/_form.html.haml
= simple_form_for @application do |f|
  - if @application.errors.any?
    #error_explanation.alert.alert-danger.pt-3.pb-2
      %h2= t('errors.template.header', model: t('application'), count: @application.errors.count)
      %ul
        - @application.errors.full_messages.each do |msg|
          %li= msg
  .container
    .panel.panel-primary
      .panel-heading
        %h2.text-center
          = t(".part_one_heading")
      .panel-body
        .row
          .col-md-4
            = f.input :organization_id, collection: @organization
          .col-md-4
            = f.input :name, label: t(".project_name")
          .col-md-4
            = f.input :coordinator, label: t(".coordinator")
        .row
          .col-md-12
            %h4.text-left
              = t(".project_costs")
        .row
          .col-md-4
            = f.input :amount_applied_for, input_html: { min: '1', required: true,  oninput: "this.value = Math.abs(this.value)"},
              label: t(".amount_applied_for")
          .col-md-4
            = f.input :amount_other_sources, input_html: { min: '0',
              required: true, oninput: "this.value = Math.abs(this.value)"},
              label: t(".amount_other_sources")
          .col-md-4
            = f.input :amount_overall, input_html: { readonly: true },
              label: t(".amount_overall")
    .panel.panel-primary
      .panel-heading
        %h2.text-center
          = t(".part_two_heading")
      .panel-body
        .container
          .form-row
            .col-md-12
              = f.input :description, label: t(".description"), input_html: {rows: '6'}
          .form-row
            .col-md-12
              .container.p-0
                %b
                  = t(".planned_location_and_date")
                .form-row
                  .col-md-8
                    = f.input :location, label: t(".location")
                  .col-md-4
                    = f.input :date, label: t(".event_date")
          .form-row
            .col-md-12
              = f.input :project_subject, label: t(".project_subject")
          .form-row
            .col-md-12
              = f.input :required_resources, label: t(".required_resources")
          .form-row
            .col-md-12
              = f.input :past_schedule, label: t(".past_schedule")
          .form-row
            .col-md-12
              = f.input :collaboration, label: t(".collaboration")
          .form-row
            .col-md-12
              = f.input :target_group, label: t(".target_group")
          .form-row
            .col-md-12
              = f.input :sponsor_enlistment, label: t(".sponsor_enlistment")
          .form-row
            .col-md-12
              = f.input :promotion_plans, label: t(".promotion_plans")
          .form-row
            .col-md-12
              = f.input :current_state, label: t(".current_state_heading")
          .container
            %h4.text-center
              = t(".experiences_heading")
            %div{"data-controller" => 'nested-form'}
              %template{"data-target" => 'nested-form.template'}
                = f.fields_for :experiences, Experience.new, child_index: 'NEW_RECORD_EXPERIENCE' do |ex|
                  = render "experiences_fields", f: ex

              = f.fields_for :experiences do |ex|
                = render "experiences_fields", f: ex
              .mb-3{"data-target" => "nested-form.links"}
                = link_to t('.add_experience_item'), "#", id: "add_experience", class: "btn btn-primary", data: { action: "click->nested-form#add_association" }
          .container
            %h4.text-center
              = t(".schedule_items_heading")
            %div{"data-controller" => 'nested-form'}
              %template{"data-target" => 'nested-form.template'}
                = f.fields_for :schedule_items, ScheduleItem.new, child_index: 'NEW_RECORD_SCHEDULE' do |si|
                  = render "schedule_fields", f: si

              = f.fields_for :schedule_items do |si|
                = render "schedule_fields", f: si
              .mb-3{"data-target" => "nested-form.links"}
                = link_to t('.add_schedule_item'), "#", id: "add_schedule_item", class: "btn btn-primary", data: { action: "click->nested-form#add_association" }
          .container
            %h4.text-center
              = t(".roles_heading")
            %div{"data-controller" => 'nested-form'}
              %template{"data-target" => 'nested-form.template'}
                = f.fields_for :roles, Role.new, child_index: 'NEW_RECORD_ROLE' do |role|
                  = render "role_fields", f: role

              = f.fields_for :roles do |role|
                = render "role_fields", f: role
              .mb-3{"data-target" => "nested-form.links"}
                = link_to t('.add_role_item'), "#", id: "add_member", class: "btn btn-primary", data: { action: "click->nested-form#add_association" }
          .container
            .row
              %h4
                = t(".attachments")
              = f.file_field :files, multiple: true
              %br
            = t(".attachments_info")
            -if decision == 'update'
              = f.hidden_field :decision, :value => 'update'
              %button.btn.btn-primary.btn-block.rounded-sm#submit_application{type: "submit"}
                = t(".save_changes")
            -elsif decision == 'new'
              %button.btn.btn-primary.btn-block.rounded-sm#submit_application{type: "submit"}
                = t(".submit")

app/views/applications/_role_fields.html.haml
= content_tag :div, class: "nested-fields", data: { new_record: f.object.new_record? } do
  .container.role_row.w-100.my-4.p-3.border.border-secondary
    .row.role_row
      .col-md-4
        = f.input :member_role, label: t(".member_role")
      .col-md-4
        = f.input :first_name, label: t(".first_name")
      .col-md-4
        = f.input :last_name, label: t(".last_name")
        .col-md-4
    %small= link_to t('.remove_role_item'), "#", class: "btn btn-primary", data: { action: "click->nested-form#remove_association" }
    = f.hidden_field :_destroy

app/views/applications/_schedule_fields.html.haml
= content_tag :div, class: "nested-fields", data: { new_record: f.object.new_record? } do
  .container.schedule_items_row.w-100.my-4.p-3.border.border-secondary
    .row
      .col-md-4
        = f.input :todo , label: t(".todo"), input_html: { class: "disable_empty" }
      .col-md-4
        = f.input :start_date, label: t('.start_date')
      .col-md-4
        = f.input :due_date, label: t(".due_date")
    %small= link_to t('.remove_schedule_item'), "#", class: "btn btn-primary", data: { action: "click->nested-form#remove_association" }
    = f.hidden_field :_destroy

app/views/applications/edit.html.haml
%h1.text-center Editing application

= render 'form', decision: 'update'

= link_to t('show'), @application
\|
= link_to t('back'), applications_path

app/views/applications/index.html.haml
= javascript_pack_tag 'applications/index', 'data-turbolinks-track': 'reload'

%h1.text-center 
  = t('.k_applications')
.table-responsive.table.table-hover.table-striped
  %table.table.table-hover
    %thead.table-primary
      %tr
        %th.align-middle 
          = t "applications.form.project_name"
        %th.align-middle
          = t "applications.form.coordinator"
        %th.align-middle 
          = t "applications.index.organization"
        %th.align-middle 
          = t "applications.index.creation_date"
        %th.align-middle
          = t "applications.index.state"

    %tbody#selectable
      - @applications.each do |application|
        %tr{:id => application.id.to_s}
          %td
            = application.name
            %a.fas.fa-eye{:href => application_path(application) }
            %a.fas.fa-pen{:href => edit_application_path(application) }
          %td= application.coordinator
          - organization = Organization.find(application.organization_id)
          %td= organization.name
          %td= application.created_at.to_formatted_s(:db)
          -if application.pending?
            %td.p-0.bg-warning.align-middle.text-center{ :id => "applicationDropdown" + application.id.to_s, "data-toggle" => "dropdown" } 
              =t('.pending')
          -elsif application.accepted?
            %td.p-0.bg-success.align-middle.text-center{ :id => "applicationDropdown" + application.id.to_s, "data-toggle" => "dropdown" } 
              =t('.accepted')
          -elsif application.rejected?
            %td.p-0.bg-danger.align-middle.text-center{ :id => "applicationDropdown" + application.id.to_s, "data-toggle" => "dropdown" } 
              =t('.rejected')
          -else
            %td

  .btn-group
    =button_to t('.select_action'), bulk_action_applications_path, method: :patch, id: "actionName", class: "button btn btn-primary btn-lg rounded-sm", disabled: true, params: {:decision => "", :selections => "" }
    %button.btn.btn-primary.btn-lg.dropdown-toggle.dropdown-toggle-split{ "data-toggle" => "dropdown"}
    .dropdown-menu
      .dropdown-item#accept
        =t('.accept')
      .dropdown-item#reject
        =t('.reject')
      .dropdown-item#delete
        =t('.delete')

app/views/applications/new.html.haml
= javascript_pack_tag 'applications/edit', 'data-turbolinks-track': 'reload'

%h1.text-center
  = t('.k_application')

= render 'form', decision: 'new'

app/views/applications/show.html.haml
%h1.text-center
  = t('.k_application')
-if policy(@application).update?
  .container.alert.alert-secondary
    .row
      .col-md-11.my-auto.text-center.text-md-left
        = t('.application_state') + ':'
        -if @application.pending?
          = t('.pending')
        -elsif @application.accepted?
          = t('.accepted')
        -elsif @application.rejected?
          = t('.rejected')
      -if @application.pending?
        .col-md-1.text-center
          .btn-group.float-md-right
            =button_to t('.accept'), application_path, params: {decision: :accept}, method: :patch, class: 'btn btn-success'
            =button_to t('.reject'), application_path, params: {decision: :reject}, method: :patch, class: 'btn btn-danger'
.container
  .panel.panel-primary
    .panel-heading
      %h2.text-center
        = t('applications.form.part_one_heading')
    .panel-body
      .container
        .card-group.mb-2
          .card
            %h5.card-header
              = t("applications.form.applying_organization") 
            .card-body
              %p.card-text
                -organization = Organization.find @application.organization_id
                =organization.name
          .card
            %h5.card-header
              = t("applications.form.project_name")
            .card-body
              %p.card-text
                =@application.name
          .card
            %h5.card-header
              = t("applications.form.coordinator")
            .card-body
              %p.card-text
                =@application.coordinator
        .row
          .col-md-12
            %h4.text-left 
              = t('applications.form.project_costs')
        .card-group.align-items-md-end.mb-3
          .card
            %h5.card-header
              = t("applications.form.amount_applied_for") 
            .card-body
              %p.card-text
                =@application.amount_applied_for
          .card
            %h5.card-header
              = t("applications.form.amount_other_sources")
            .card-body
              %p.card-text
                =@application.amount_other_sources
          .card
            %h5.card-header
              = t("applications.form.amount_overall")
            .card-body
              %p.card-text
                =@application.amount_overall
  .panel.panel-primary
    .panel-heading
      %h2.text-center
        = t('applications.form.part_two_heading')
    .panel-body
      .container
        .form-row
          .col-md-12
            .card.mb-3
              %h5.card-header
                = t("applications.form.description")
              .card-body
                %p.card-text
                  =@application.description
        - if !@application.location.nil? || !@application.date.nil? 
          .card-group.mb-3.form-row.px-1
            - if !@application.location.nil?
              .card.col-md-8.px-0
                %h5.card-header
                  = t("applications.form.location")
                .card-body
                  %p.card-text
                    = @application.location
            - if !@application.date.nil?
              .card.col-md-4.px-0
                %h5.card-header
                  = t("applications.form.event_date")
                .card-body
                  %p.card-text
                    = @application.date.to_s
        .form-row
          .col-md-12
            .card.mb-3
              %h5.card-header
                = t("applications.form.project_subject")
              .card-body
                %p.card-text
                  =@application.project_subject
            .card.mb-3
              %h5.card-header
                = t("applications.form.required_resources")
              .card-body
                %p.card-text
                  =@application.required_resources
            .card.mb-3
              %h5.card-header
                = t("applications.form.past_schedule")
              .card-body
                %p.card-text
                  =@application.past_schedule
            .card.mb-3
              %h5.card-header
                = t("applications.form.collaboration")
              .card-body
                %p.card-text
                  =@application.collaboration
            .card.mb-3
              %h5.card-header
                = t("applications.form.target_group")
              .card-body
                %p.card-text
                  =@application.target_group
            .card.mb-3
              %h5.card-header
                = t("applications.form.sponsor_enlistment")
              .card-body
                %p.card-text
                  =@application.sponsor_enlistment
            .card.mb-3
              %h5.card-header
                = t("applications.form.promotion_plans")
              .card-body
                %p.card-text
                  =@application.promotion_plans

      .container
        %h4.text-center 
          = t("applications.form.experiences_heading") + ':'
        %table.table.table-hover.table-striped.mb-3
          %thead.table-primary
            %tr
              %th
                = t("applications.form.project_name") 
              %th
                = t("applications.form.role") 
              %th
                = t("applications.form.budget") 
              %th
                = t("applications.form.project_date") 
              %th
                = t("applications.form.member_name") 
          %tbody
            - @application.experiences.each do |experience|
              %tr
                %td
                  = experience.project_name
                %td
                  = experience.role
                %td
                  = experience.budget
                %td
                  = experience.project_date.to_s
                %td
                  = experience.member_name

      .container
        %h4.text-center 
          = t("applications.form.schedule_items_heading")
        %table.table.table-hover.table-striped
          %thead.table-primary
            %tr
              %th
                = t("applications.form.todo") 
              %th
                = t("applications.form.start_date") 
              %th
                = t("applications.form.due_date") 
          %tbody
            - @application.schedule_items.each do |si|
              %tr
                %td
                  = si.todo
                %td
                  = si.start_date.to_s
                %td
                  = si.due_date.to_s
      .container
        .form-row
          .col-md-12
            .card.mb-3
              %h5.card-header
                = t("applications.form.current_state_heading")
              .card-body
                %p.card-text
                  =@application.current_state

      .container
        %h4.text-center 
          = t("applications.form.roles_heading")
        %table.table.table-hover.table-striped
          %thead.table-primary
            %tr
              %th
                = t("applications.form.todo") 
              %th
                = t("applications.form.start_date") 
              %th
                = t("applications.form.due_date") 
          %tbody
            - @application.roles.each do |role|
              %tr
                %td
                  = role.member_role
                %td
                  = role.first_name
                %td
                  = role.last_name
  .panel.panel-primary#attachments
    .panel-heading
      %h2.text-center 
        = t('applications.form.attachments')
    .panel-body
      - @application.files.each do |file|
        %a{href: rails_blob_path(file, disposition: "attachment")}=file.filename