config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :organizations
  resources :applications do
    collection do
      patch 'bulk_action'
    end
  end
  resources :applications
  root 'pages#home'
  get "/", to: "pages#home"
  # Add basic UI for viewing applications
  devise_for :users
  resources :faculties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-sm.navbar-light.bg-primary.mb-sm-5
  .container-fluid
    .navbar-header.mx-auto
      .navbar-brand.mx-auto
        = t(".funding")
    %ul.navbar-nav.mx-auto
      %li.nav-item.mx-auto
        = link_to t(".main_page"), root_path, class: "nav-link"
      - if !current_user.nil? && current_user.admin?
        %li.nav-item.mx-auto
          = link_to t(".organizations"), organizations_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".new_application"), new_application_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".applications"), applications_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".faculties"), faculties_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "nav-link"
      -elsif current_user
        %li.nav-item.mx-auto
          = link_to t(".new_application"), new_application_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".applications"), applications_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".faculties"), faculties_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "nav-link"
      -else
        %li.nav-item.mx-auto
          = link_to t(".log_in"), new_user_session_path, class: "nav-link"
        %li.nav-item.mx-auto
          = link_to t(".sign_up"), new_user_registration_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{ name:"viewport",
            content:"width=device-width, initial-scale=1, shrink-to-fit=no"}
    = csrf_meta_tags
    %title Finansowanie
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload'
  %body.bg-gradient-secondary
    %header
      = render 'layouts/header'
    .container.bg-light.rounded.py-4
      .row
        .col-md-12
      .row
        .col-md-5
          - flash.each do |key, value|
            %div{class: "#{flash_class(key)}"}
              = value
      .row
        .col-md-12
          = yield